[package]
name = "launcher"
version = "0.1.0"
edition = '2018'

[build]
target-dir = "dist"

[dependencies]
serde_json = "1.0.68"
serde = "1.0.130"
notify-rust = "4"
cluFlock = "1.2.5"
nfd2 = "0.3.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"